---
title: "Figure"
output: html_document
date: '2022-07-21'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(multcomp)
library(ggplot2)
cbbpalette <- c( "#009E73", "#e79f00", "#9ad0f3", "#0072B2", "#D55E00", 
    "#CC79A7","#000000", "#F0E442") #colorblind and grayscale friendly.
```


Load the final model
```{r}
load("~/MAIHDA/Evaluation/eval_df.rda")
load("~/MAIHDA/Evaluation/sum_eval_df.rda")

eval_df <- eval_df %>%
  filter(model != "Bay.") %>%
  mutate(model = ifelse(model=="Freq.","Traditional","MAIHDA"),
         model = factor(model, levels = c("Traditional", "MAIHDA")))


```


Difference from true score disag
```{r}
ggplot(data=eval_df, aes(x=N_groups, y=dif, color=N_fac)) +

  geom_jitter(shape = 19,size=.05,  alpha=0.3, width=0.2) + 
 guides(colour = guide_legend(override.aes = list(size=5, alpha=1))) +

  theme(legend.position = "right",  axis.text.x=element_text(angle=0) , axis.ticks.x=element_blank(),panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank(), axis.line = element_line(colour = "black"),text = element_text(size=16, color = "black")) +
  scale_color_manual(values=cbbpalette) +
  labs(color="Total sample \nsize", x="Sub-group sample size") +

  ylab("True Error")  +
  scale_x_continuous(trans='log10') +
    geom_hline(yintercept=0, alpha = 0.3) +
    facet_grid(model ~ .) 

#Saves the image
ggsave("~/MAIHDA/Figures/Score_disag.png", plot= last_plot(), dpi=300, width = 7.3, height = 3.25, units = "in", device = "png")
```

Box plot for true error by sub-group sample size
```{r}


ggplot(data=filter(eval_df,  N_groups<20), aes(x=as.factor(N_groups), y=dif, color=N_fac)) +

  geom_boxplot(outlier.shape=NA) +
  # geom_jitter(shape = 19,size=.05,  alpha=0.3, width=0.0) + 
 guides(colour = guide_legend(override.aes = list(size=1, alpha=1))) +

  theme(legend.position = "right",  axis.text.x=element_text(angle=0) , axis.ticks.x=element_blank(),panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank(), axis.line = element_line(colour = "black"),text = element_text(size=16, color = "black")) +
  scale_color_manual(values=cbbpalette) +
  labs(color="Total sample \nsize", x="Sub-group sample size") +

  ylab("True Error")  +
  # scale_y_continuous(limits = c(-30,30)) +
    geom_hline(yintercept=0, alpha = 0.3) +
      facet_grid(model ~ N_fac) 

#Saves the image
ggsave("~/MAIHDA/Figures/True_error_box_20.png", plot= last_plot(), dpi=300, width = 7.3, height = 3.25, units = "in", device = "png")

ggplot(data=filter(eval_df,  N_groups>20 & N_groups<50), aes(x=as.factor(N_groups), y=dif, color=N_fac)) +

  geom_boxplot(outlier.shape=NA) +
  # geom_jitter(shape = 19,size=.05,  alpha=0.3, width=0.0) + 
 guides(colour = guide_legend(override.aes = list(size=1, alpha=1))) +

  theme(legend.position = "right",  axis.text.x=element_text(angle=0) , axis.ticks.x=element_blank(),panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank(), axis.line = element_line(colour = "black"),text = element_text(size=16, color = "black")) +
  scale_color_manual(values=cbbpalette) +
  labs(color="Total sample \nsize", x="Sub-group sample size") +

  ylab("True Error")  +
  # scale_y_continuous(limits = c(-30,30)) +
    geom_hline(yintercept=0, alpha = 0.3) +
      facet_grid(model ~ N_fac) 

#Saves the image
ggsave("~/MAIHDA/Figures/True_error_box_50.png", plot= last_plot(), dpi=300, width = 7.3, height = 3.25, units = "in", device = "png")


```

SE disag
```{r}
#x= sets what variable you want on the x axis. 
#group= sets what groups you want within each term on the x axis. 
#color= what groups should define the different colors you use. 
#shape = sets what term defines the symbols that are used for the points.
ggplot(data=eval_df, aes(x=N_groups, y=SE, color=N_fac)) +
  geom_jitter(shape = 19,size=.05,  alpha=0.3, width=0.2) + 
   guides(colour = guide_legend(override.aes = list(size=5, alpha=1))) +
  theme(legend.position = "right",  axis.text.x=element_text(angle=0) , axis.ticks.x=element_blank(),panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank(), axis.line = element_line(colour = "black"),text = element_text(size=16, color = "black")) +
  
  scale_color_manual(values=cbbpalette) +
  # set the y-axis label
  ylab("Estimated Standard Error")  +
    labs(color="Total sample \nsize", x="Sub-group sample size") +
   scale_x_continuous(trans='log10') +
    geom_hline(yintercept=0, alpha = 0.3) +
    facet_grid(model ~ .) 
  #set the y-axis scale
  # scale_y_continuous(breaks=seq(-15, 15, 5)) 

#Saves the image
ggsave("~/MAIHDA/Figures/SE_disag.png", plot= last_plot(), dpi=300, width = 7.3, height = 3.25, units = "in", device = "png")
```

violin plot function
```{r}
violin_group_fun <- function(Data, Group, Title, Upper){

    ggplot(data=filter(Data, group==Group), aes(x=model, y=dif_abs, color=N_fac)) +
    scale_color_manual(values=cbbpalette) +
  geom_point( shape = 19,size=1, position = "jitter",  alpha=.1)+
     geom_violin(alpha=0.1, position = position_dodge(width = .75),size=.5,color="black") +
    geom_boxplot(notch = TRUE,  outlier.size = -1, color="black",lwd=0.6, alpha = 0.1)+
   guides(colour = guide_legend(override.aes = list(size=5, alpha=1))) +
  # geom_violin(trim=TRUE) +
  # geom_point(position = "jitter", size=1, alpha=0.2) + 
  # gemo_errorbar sets the error bars
  # geom_errorbar(aes( ymax= Q+SE, ymin=Q-SE), position="dodge")+
  #Theme() is setting the key and some other stuff
  theme(legend.position = "right",  axis.text.x=element_text(angle=0) , axis.title.x = element_blank(), axis.ticks.x=element_blank(),panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank(), axis.line = element_line(colour = "black"),text = element_text(size=16, color = "black")) +
  # set the y-axis label
labs(y="Mean True Error",color="Total sample \nsize", title = Title) +
  
  facet_grid(. ~ N_fac) +
  #   xlab("Sample Size")  +
  # ylab("Mean Difference from True Score")  +

  #set the y-axis scale
  scale_y_continuous(limits=c(-1,Upper)) 
  }
```

Difference from true score
```{r}
violin_group_fun(eval_df,"CG White men","CG White men",60)
ggsave("~/MAIHDA/Figures/Score_CGWM.png", plot= last_plot(), dpi=300, width = 7.3, height = 3.25, units = "in", device = "png")

violin_group_fun(eval_df,"FG Black women","FG Black women",60)
ggsave("~/MAIHDA/Figures/Score_FGBW.png", plot= last_plot(), dpi=300, width = 7.3, height = 3.25, units = "in", device = "png")

```

Combined plot
```{r}
    ggplot(data=filter(eval_df, N_fac==500), aes(x=model, y=dif_abs, color=model)) +
scale_color_manual(values=cbbpalette) +
  geom_point( shape = 19,size=1, position = "jitter",  alpha=.1)+
     geom_violin(alpha=0.1, position = position_dodge(width = .75),size=.5,color="black") +
    geom_boxplot(notch = TRUE,  outlier.size = -1, color="black",lwd=0.6, alpha = 0.1)+
   guides(colour = guide_legend(override.aes = list(size=5, alpha=1))) +
  # geom_violin(trim=TRUE) +
  # geom_point(position = "jitter", size=1, alpha=0.2) + 
  # gemo_errorbar sets the error bars
  # geom_errorbar(aes( ymax= Q+SE, ymin=Q-SE), position="dodge")+
  #Theme() is setting the key and some other stuff
  theme(legend.position = "right",  axis.text.x=element_blank(), axis.title.x = element_blank(), axis.ticks.x=element_blank(),panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank(), axis.line = element_line(colour = "black"),text = element_text(size=16, color = "black")) +
  # set the y-axis label
labs(y="Mean True Error",color="Total sample \nsize", title = "Compound plot (N_sample=500)") +
  
  facet_wrap(~ group, ncol=4) +
  #   xlab("Sample Size")  +
  # ylab("Mean Difference from True Score")  +

  #set the y-axis scale
  scale_y_continuous(limits=c(-1,60)) 

ggsave("~/MAIHDA/Figures/Score_compound.png", plot= last_plot(), dpi=300, width = 11, height = 6, units = "in", device = "png")
```

Difference from true score (mean)
```{r}
#x= sets what variable you want on the x axis. 
#group= sets what groups you want within each term on the x axis. 
#color= what groups should define the different colors you use. 
#shape = sets what term defines the symbols that are used for the points.
ggplot(data=sum_eval_df, aes(x=model, y=mean_dif, color=N_fac)) +
 # , color= Degree, shape = Gender
  #geom_point sets it as points on the plot (as apposed to geom_bar which would give a bar graph)
  geom_point( shape = 19,size=1, position = "jitter",  alpha=.1)+
     geom_violin(alpha=0.1, position = position_dodge(width = .75),size=.5,color="black") +
    geom_boxplot(notch = TRUE,  outlier.size = -1, color="black",lwd=0.6, alpha = 0.1)+
   guides(colour = guide_legend(override.aes = list(size=5, alpha=1))) +
  # geom_violin(trim=TRUE) +
  # geom_point(position = "jitter", size=1, alpha=0.2) + 
  # gemo_errorbar sets the error bars
  # geom_errorbar(aes( ymax= Q+SE, ymin=Q-SE), position="dodge")+
  #Theme() is setting the key and some other stuff
  theme(legend.position = "right",  axis.text.x=element_text(angle=0) , axis.title.x = element_blank(), axis.ticks.x=element_blank(),panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank(), axis.line = element_line(colour = "black"),text = element_text(size=16, color = "black")) +
  # set the y-axis label
labs(y="Mean True Error",color="Total sample \nsize") +
  
  facet_grid(. ~ N_fac) +
  #   xlab("Sample Size")  +
  # ylab("Mean Difference from True Score")  +

  #set the y-axis scale
  scale_y_continuous(limits=c(0,14)) 
    #breaks=seq(-2, 2, .5),limits=c(-2,2)) 

#Saves the image
ggsave("~/MAIHDA/Figures/Score.png", plot= last_plot(), dpi=300, width = 7.3, height = 3.25, units = "in", device = "png")
```


SE
```{r}
#x= sets what variable you want on the x axis. 
#group= sets what groups you want within each term on the x axis. 
#color= what groups should define the different colors you use. 
#shape = sets what term defines the symbols that are used for the points.
ggplot(data=sum_eval_df, aes(x=model, y=mean_SE, color=N_fac)) +
 # , color= Degree, shape = Gender
  #geom_point sets it as points on the plot (as apposed to geom_bar which would give a bar graph)
  geom_point( shape = 19,size=1, position = "jitter",  alpha=.1)+
     geom_violin(alpha=0.1, position = position_dodge(width = .75),size=.5,color="black") +
    geom_boxplot(notch = TRUE,  outlier.size = -1, color="black",lwd=0.6, alpha = 0.1)+
     guides(colour = guide_legend(override.aes = list(size=5, alpha=1))) +
  # gemo_errorbar sets the error bars
  # geom_errorbar(aes( ymax= Q+SE, ymin=Q-SE), position="dodge")+
  #Theme() is setting the key and some other stuff
  theme(legend.position = "right",  axis.text.x=element_text(angle=0) , axis.title.x = element_blank(), axis.ticks.x=element_blank(),panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank(), axis.line = element_line(colour = "black"),text = element_text(size=16, color = "black")) +
  # set the y-axis label
  labs(y="Mean Estimated Standard Error",color="Total sample")+
    facet_grid(. ~ N_fac) +
  #set the y-axis scale
  scale_y_continuous(limits=c(0,9.5)) 

#Saves the image
ggsave("~/MAIHDA/Figures/SE.png", plot= last_plot(), dpi=300, width = 7.3, height = 3.25, units = "in", device = "png")
```

Bias (using eval_df)
```{r}
ggplot(data=eval_df, aes(x=N_groups, y=dif, color=N_fac)) +

  geom_smooth(se=TRUE, span=5) + 
 guides(colour = guide_legend(override.aes = list(size=5, alpha=1))) +

   theme(legend.position = "right",  axis.text.x=element_text(angle=0) , axis.ticks.x=element_blank(),panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank(), axis.line = element_line(colour = "black"),text = element_text(size=16, color = "black")) +
   scale_color_manual(values=cbbpalette) +
   labs(color="Total sample \nsize", x="Sub-group sample size") +
  # 
   ylab("True Error")  +
   scale_x_continuous(trans='log10') +
  geom_hline(yintercept=0, alpha = 0.3) +
   facet_grid(model ~ .) 

ggsave("~/MAIHDA/Figures/Bias_LOESS.png", plot= last_plot(), dpi=300, width = 7.3, height = 3.25, units = "in", device = "png")
```

Bias + points (using eval_df)
```{r}
ggplot(data=eval_df, aes(x=N_groups, y=dif, color=N_fac)) +

  geom_jitter(shape = 19,size=.05,  alpha=0.3, width=0.2) + 
  geom_smooth(alpha=0.5) +
 guides(colour = guide_legend(override.aes = list(size=5, alpha=1))) +

  theme(legend.position = "right",  axis.text.x=element_text(angle=0) , axis.ticks.x=element_blank(),panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank(), axis.line = element_line(colour = "black"),text = element_text(size=16, color = "black")) +
  scale_color_manual(values=cbbpalette) +
  labs(color="Total sample \nsize", x="Sub-group sample size") +

  ylab("True Error")  +
  scale_x_continuous(trans='log10') +
    geom_hline(yintercept=0, alpha = 0.3) +
    facet_grid(model ~ .) 

ggsave("~/MAIHDA/Figures/Bias_point_LOESS.png", plot= last_plot(), dpi=300, width = 7.3, height = 3.25, units = "in", device = "png")
```


Bias (using bias df)
```{r}
ggplot(data=bias_df, aes(x=N_groups, y=bias, color=N_fac)) +

  geom_line() + 
 guides(colour = guide_legend(override.aes = list(size=5, alpha=1))) +

   theme(legend.position = "right",  axis.text.x=element_text(angle=0) , axis.ticks.x=element_blank(),panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank(), axis.line = element_line(colour = "black"),text = element_text(size=16, color = "black")) +
   scale_color_manual(values=cbbpalette) +
   labs(color="Total sample \nsize", x="Sub-group sample size") +
  # 
   ylab("Bias")  +
   scale_x_continuous(trans='log10') +
  geom_hline(yintercept=0, alpha = 0.3) +
   facet_grid(model ~ .) 

#Saves the image
ggsave("~/MAIHDA/Figures/Bias_point.png", plot= last_plot(), dpi=300, width = 7.3, height = 3.25, units = "in", device = "png")
```

